
#npl concept

In [ ]:
text="hello! World is this IS Ibrahim"
text_lower=text.lower()
print(text_lower)

hello! world is this is ibrahim


In [ ]:
import re
text_clean=re.sub(r'[^a-z]','',text)
print(text_clean)

helloorldisthisbrahim


One-line definition:

NLTK is a Python library used to process and analyze human language text.

What can NLTK do?

✅ Tokenization (split text into words/sentences)
✅ Stopword Removal (remove common words like "is", "the", "and")
✅ Stemming (reduce words to root form)
✅ Lemmatization (convert words to meaningful base form)
✅ Part-of-Speech (POS) Tagging
✅ Sentiment Analysis
✅ Text Classification

In [ ]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords',quiet=True)
stop_word=set(stopwords.words('english'))
text="hello! World  this iS Ibrahim"
token=[]
for word in text.split():
  if word not in stop_word:
    token.append(word)
print(token)

['hello!', 'World', 'iS', 'Ibrahim']


In [ ]:
import nltk
nltk.download('punkt_tab',quiet=True)
from nltk.tokenize import word_tokenize

text="hello! World  this iS Ibrahim"
basic=text.split()
print(basic)
token=word_tokenize(text.lower())
print(token)

['hello!', 'World', 'this', 'iS', 'Ibrahim']
['hello', '!', 'world', 'this', 'is', 'ibrahim']


👉 Stemming removes word endings to get the root word, even if the result is not a proper dictionary word.


👉 Lemmatization converts a word to its actual dictionary base form using language rules.

In [ ]:
import nltk
from nltk.stem import PorterStemmer,WordNetLemmatizer
nltk.download('wordnet',quiet=True)
stemmer=PorterStemmer()
lemmatizer=WordNetLemmatizer()
words=['running','gaming','ibrahim','caring','abubakar']
for word in words:
  stem = stemmer.stem(word)
  lemma = lemmatizer.lemmatize(word,pos='v')
  print(f"Word: {word:12}, Stem: {stem:10}, Lemma: {lemma}")

Word: running     , Stem: run       , Lemma: run
Word: gaming      , Stem: game      , Lemma: game
Word: ibrahim     , Stem: ibrahim   , Lemma: ibrahim
Word: caring      , Stem: care      , Lemma: care
Word: abubakar    , Stem: abubakar  , Lemma: abubakar


In [ ]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
nltk.download('stopwords', quiet=True)
nltk.download('wordnet', quiet=True)
nltk.download('punkt', quiet=True)
stop_words=set(stopwords.words('english'))
lemmatizer=WordNetLemmatizer()
def preprocess(text):
  text = text.lower()
  text=re.sub(r'[^a-z ]',' ',text)
  token=text.split()
  filter_token=[]
  for w in token:
    if w not in stop_words:
      filter_token.append(w)
  tokens=filter_token
  lemmatized_token=[]
  for w in tokens:
    lemmatized_token.append(lemmatizer.lemmatize(w))
  tokens=lemmatized_token
  return tokens
text="hello! World  this iS Ibrahim"
print(preprocess(text))

['hello', 'world', 'ibrahim']


In [4]:
from sklearn.feature_extraction.text import CountVectorizer
email={
    'cricket match cricket match ',
    'free win money free  win money',
    'cricket match free win money cricket'
}
cv=CountVectorizer()
x=cv.fit_transform(email).toarray()
print('vocabullary: ',cv.get_feature_names_out())
print('bow matrix')
print(x)

vocabullary:  ['cricket' 'free' 'match' 'money' 'win']
bow matrix
[[0 2 0 2 2]
 [2 0 2 0 0]
 [2 1 1 1 1]]


. TF (Term Frequency)

Measures how many times a word appears in a document.

2. TF-IDF (Term Frequency–Inverse Document Frequency)

Gives importance to a word based on:

How often it appears in a document (TF)
How rare it is across all documents (IDF)

Formula:

These are parameters commonly used in TfidfVectorizer in NLP.

1. sublinear_tf=True

Replaces term frequency (TF) with logarithmic scaling.

2. max_df

Ignores words that appear in too many documents.

3. min_df

Ignores words that appear in too few documents.

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer
email={
    'cricket match cricket match ',
    'free win money free  win money',
    'cricket match free win money cricket'
}
tfidf=TfidfVectorizer( sublinear_tf=True,max_df=0.95,min_df=1)
x=tfidf.fit_transform(email).toarray()
print('feature names: ',tfidf.get_feature_names_out())
print('tfidf matrix')
import numpy as np
print(np.round(x,3))

feature names:  ['cricket' 'free' 'match' 'money' 'win']
tfidf matrix
[[0.    0.577 0.    0.577 0.577]
 [0.707 0.    0.707 0.    0.   ]
 [0.646 0.382 0.382 0.382 0.382]]
