data visualisation:  Representing data that includes piechart,graphs etc...

In [ ]:
!pip install numpy

In [ ]:
import numpy as np
print(np.__version__)

2.0.2


In [ ]:
#1d array=vector
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
#2d array=matrice
b=np.array([[1,2,3],
           [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
c=np.array([
    [
        [1,2],
        [3,4]
    ],
        [
            [5,6],
            [5,4]
        ]
    ]
)
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [5 4]]]


In [ ]:
a=np.zeros([2,3])
b=np.ones([2,3])
c=np.full([2,3],9)
d=np.eye(4)
print((a,b,c,d))

(array([[0., 0., 0.],
       [0., 0., 0.]]), array([[1., 1., 1.],
       [1., 1., 1.]]), array([[9, 9, 9],
       [9, 9, 9]]), array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]]))


In [ ]:
f=np.arange(2,10,3)
print(f)

[2 5 8]


In [ ]:
np.linspace(1,4,3)

array([1. , 2.5, 4. ])

In [18]:
np.random.rand(2,3)

array([[0.66360094, 0.26872916, 0.90465671],
       [0.618126  , 0.41603258, 0.14041657]])

In [19]:
np.random.randint(1,5,size=(2,3))

array([[3, 2, 3],
       [2, 1, 4]])

In [20]:
np.random.randn(2,3)

array([[ 0.64316192, -1.06164339,  0.21267134],
       [ 1.47413732,  0.57806107, -0.30224705]])

In [23]:
arr=np.array(["a","b","c","d","e"])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.nbytes)

(5,)
1
5
<U1
4
20


In [25]:
a=np.array([10,20,30,40,50])
print(a[0])
print(a[2])
print(a[-1])

10
30
50


In [26]:
print(a[1:4])
print(a[:3])
print(a[:3])
print(a[::2])
print(a[::-1])

[20 30 40]
[10 20 30]
[10 20 30]
[10 30 50]
[50 40 30 20 10]


In [27]:
n=np.array([[1,2,3],
            [3,4,5]])
print(n[0,0])
print(n[1,2])

1
5


In [28]:
print(n[0,:])
print(n[:,1])

[1 2 3]
[2 4]


In [29]:
a=np.array([1,2,3])
mask = a>1
print(mask)
print(a[mask])

[False  True  True]
[2 3]


In [31]:
print(a[a>1])
print(a[[0,2]])

[2 3]
[1 3]
